services:
    _defaults:
        autowire: true
        autoconfigure: true

    Pantheon\EventBundle\:
        resource: '../../*'
        exclude: '../../{DependencyInjection,DTO,Entity,Migrations,Tests,Security/Event,Kernel.php}'